compatible: "pixart,pmw3610"
description: PixArt PMW3610 Optical Sensor

include: spi-device.yaml

properties:
  irq-gpios:
    type: phandle-array
    description: Interrupt GPIO

  motion-gpios:
    type: phandle-array
    description: Motion GPIO

  zephyr,axis-x:
    type: int
    required: true

  zephyr,axis-y:
    type: int
    required: true

  scroll-layers:
    type: array
    description: Layers used for scrolling
